
  # FastAPI, postgres a pgAdmin běžící v oddělených kontejnerech
  # FastApi - vyvtoření databázové strukutury v pythonu
  # postgres - databázový systém
  # pgAdmin - uživatelské rozhraní, které umožňuje administraci dat v databázi
version: "3.9"
services:
  python_fastapi:
    image: python_fastapi
    build:
      context: ./pyf
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=data
    depends_on:
      - postgres
    ports:
      - 80:8000  
    restart: "always"  
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=data
    ports:
      - 5432:5432
    restart: "always"
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=anoyne@anywhere.com
      - PGADMIN_DEFAULT_PASSWORD=example
    ports:
      - 50011:80
