version: "3.9"

services:
  python_fastapi:
    image: python_fastapi
    build:
      context: ./pyf
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=data
    depends_on:
      - postgres

  js:
    image: js
    build: 
      context: ./js
    environment:
      NODE_ENV: development

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=data
    
  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
    depends_on:
      - postgres
      - js
      - python_fastapi
